% Algorithm list $Id$
function algs= get_list_of_algs;

algs = {'Recon_Sheffield_backproj', ...
        'Recon_NOSER_ndiff', ...
        'Recon_NOSER_diff', ...
        'Recon_GREIT_ndiff', ...
       };
