# Create Simulated data for GREIT evaluations
# Usage set MATLAB 

ifndef MATLAB
   MATLAB = C:/progra~1/matlab6p5/bin/win32/matlab.exe -nosplash
   EIDORSTARTUP = ../../
endif

# CREATE NETGEN TANK MODEL
ng_tank.mat: simulation_3d_test00.m
	$(MATLAB)
