function data= np_fwd_solve( fwd_model, image)
% Fwd solver for Nick Polydorides EIDORS3D code
% $Id: np_fwd_solve.m,v 1.1 2004-07-09 18:51:28 aadler Exp $

mat_ref= image; %% TODO: make object

elec= zeros(length(fwd_model.electrode ), ...
            length(fwd_model.electrode(1).nodes) );
zc  = zeros(length(fwd_model.electrode ), 1);

for i=1:length(fwd_model.electrode);
    elec(i,:)= fwd_model.electrode(i).nodes;
    zc(i)    = fwd_model.electrode(i).z_contact;
end

[I,Ib] = set_3d_currents(fwd_model.misc.protocol, ...
                         elec, ...
                         fwd_model.nodes, ...
                         fwd_model.gnd_node, ...
                         fwd_model.misc.no_pl);

%Set the tolerance for the forward solver
tol = 1e-5;

[Eref,D,Ela,ppr] = fem_master_full( ...
                fwd_model.nodes, ...
                fwd_model.elems, ...
                mat_ref, ...
                fwd_model.gnd_node, ...
                elec, ...
                zc, ...
                fwd_model.misc.sym);
[Vref] = forward_solver(fwd_model.nodes,Eref,I,tol,ppr);
[refH,refV,indH,indV,dfr]=get_3d_meas(elec,fwd_model.nodes,Vref,Ib, ...
                fwd_model.misc.no_pl);
dfr = dfr(1:2:length(dfr)); %Taking just the horrizontal measurements

data= dfr;
