package org.openeit.oeit.v1.validation;

public enum FilePattern {
	VERSION, HEADER_DIR, DEVICE, ELECTRODE, SUBJECT, PATIENT, RAW_DIR, RAW, EIT_DIR, EIT_MANIFEST, EIT_DATA_DIR, EIT_DATA, EIT_DATA_BASE, EIT_CONFIG_DIR, EIT_CONFIG, EIT_CONFIG_BASE, EIT_LOG_DIR, EIT_LOG, OPTIONAL_DATA_DIR, OPTIONAL_DATA, AUXILIARY_DIR, AUXILIARY_DATA
}
