Description of aa_inv_solve
Home > eidors > algorithms > a_adler > aa_inv_solve.m
aa_inv_solve
PURPOSE
AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
SYNOPSIS
function img= aa_inv_solve(inv_model, data1, data2)
DESCRIPTION
 AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
 img= aa_inv_solve( inv_model, data1, data2)
 img        => output image (or vector of images)
 inv_model  => inverse model struct
 data1      => differential data at earlier time
 data2      => differential data at later time
 both data1 and data2 may be matrices (MxT) each of
  M measurements at T times
 if either data1 or data2 is a vector, then it is expanded
  to be the same size matrix
CROSS-REFERENCE INFORMATION
This function calls:
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
calc_difference_data CALC_DIFFERENCE_DATA: calculate difference data between
calc_hyperparameter CALC_HYPERPARAMETER: calculate hyperparameter value
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
select_imdl SELECT_IMDL: select pre-packaged inverse model features