Description of calc_GREIT_RM
Home > eidors > algorithms > a_adler > calc_GREIT_RM.m
calc_GREIT_RM
PURPOSE
CALCULATE GREIT reconstruction matrix
SYNOPSIS
function RM= calc_GREIT_RM(vh,vi, xyc, radius, weight, options)
DESCRIPTION
 CALCULATE GREIT reconstruction matrix
   RM= calc_GREIT_RM(vh,vi, xyc, radius, weight, normalize)
 Input:
   vh     = homogeneous (reference) training measurements
   vi     = inhomogeneous training measurements
   xyc    = x,y position of targets 2xN
   radius = requested resolution matrix
      if scalar - apply resolution to all images:  recommend 0.25 for 16 elecs
   weight = weighting matrix
      if scalar   = weighting of noise vs signal
      if 32^2 x N = weighting of each image output
   options.normalize =
            0 -> regular difference EIT
            1 -> normalized difference EIT
   options.meshsz = [xmin xmax ymin ymax] size of mesh
      defaults to [-1 1 -1 1]
   options.imgsz  = [xsz ysz] size of the reconstructed image in pixels
 (C) 2009 Andy Adler. Licenced under GPL v2 or v3
 $Id: calc_GREIT_RM.m 2469 2011-03-02 16:33:04Z bgrychtol $
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_GREIT_model_mine MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach