Description of laplace_image_prior
laplace_image_prior
PURPOSE
LAPLACE_IMAGE_PRIOR calculate image prior
SYNOPSIS
function Reg= laplace_image_prior(inv_model);
DESCRIPTION
 LAPLACE_IMAGE_PRIOR calculate image prior
 Reg= laplace_image_prior( inv_model )
 Reg        => output regularization term
 inv_model  => inverse model struct
 This image prior is intended to be used as
  R'*R, but may be used as R for as well.
 The Laplace prior is a 2nd order high pass filter.
 On a rectangular mesh, it is a convolution with
   [-1,-1,-1;      [ 0;-1; 0
    -1, 8,-1    or  -1; 4;-1
    -1,-1,-1]        0;-1; 0]
 On a finite element mesh, we define the it as
 -1 for each adjacent element, and 3 (in 2D) or 4 (in 3D)
 for the element itself
CROSS-REFERENCE INFORMATION
This function calls:
aa_fwd_parameters AA_FWD_PARAMETERS: data= aa_fwd_solve(fwd_model, image)
This function is called by:
aa_e_move_image_prior AA_E_MOVE_IMAGE_PRIOR calculate image prior
compare_2d_algs Compare different 2D reconstructions
select_imdl SELECT_IMDL: select pre-packaged inverse model features
calc_model_prior_test Verify model prior calcs
SUBFUNCTIONS
function elems= find_adjoin(ee, ELEM)
SOURCE CODE
function Reg= laplace_image_prior(inv_model);
% LAPLACE_IMAGE_PRIOR calculate image prior
% Reg= laplace_image_prior(inv_model)
% Reg        => output regularization term
% inv_model  => inverse model struct
%
% This image prior is intended to be used as
%  R'*R, but may be used as R for as well.
%
% The Laplace prior is a 2nd order high pass filter.
% On a rectangular mesh, it is a convolution with
%   [-1,-1,-1;      [ 0;-1; 0
%    -1, 8,-1    or  -1; 4;-1
%    -1,-1,-1]        0;-1; 0]
%
% On a finite element mesh, we define the it as
% -1 for each adjacent element, and 3 (in 2D) or 4 (in 3D)
% for the element itself
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
pp= aa_fwd_parameters(inv_model.fwd_model);
Reg = speye(pp.n_elem);
   Iidx= [];
   Jidx= [];
   Vidx= [];
   for ii=1:pp.n_elem
     el_adj = find_adjoin( ii, pp.ELEM );
     for jj=el_adj(:)'
         Iidx= [Iidx, ii, ii, jj, jj];
         Jidx= [Jidx, ii, jj, ii, jj];
         Vidx= [Vidx,  1, -1, -1,  1];
     end
   end
   Reg = sparse(Iidx,Jidx, Vidx, pp.n_elem, pp.n_elem );
% find elems which are connected to elems ee
function elems= find_adjoin(ee, ELEM)
   nn= ELEM(:,ee);
   [d,e]= size(ELEM);
   ss= zeros(1,e);
   for i=1:d
     ss= ss+ any(ELEM==nn(i));
   end
   elems= find(ss==d-1);