Description of noser_image_prior
noser_image_prior
PURPOSE
NOSER_IMAGE_PRIOR calculate image prior
SYNOPSIS
function Reg= noser_image_prior(inv_model);
DESCRIPTION
 NOSER_IMAGE_PRIOR calculate image prior
 Reg= noser_image_prior( inv_model )
 Reg        => output regularization term
 inv_model  => inverse model struct
 Prior is diag( diag(J'*J)^exponent )
 param is normally .5, this value can be changed by
 setting inv_model.noser_image_prior.exponent= new_value
CROSS-REFERENCE INFORMATION
This function calls:
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
This function is called by:
moving_tank_objs MOVING_TANK_OBJS: create movies of objects moving in tanks
mk_common_model MK_COMMON_MODEL: make common EIT models
select_imdl SELECT_IMDL: select pre-packaged inverse model features
calc_model_prior_test Verify model prior calcs
SOURCE CODE
function Reg= noser_image_prior(inv_model);
% NOSER_IMAGE_PRIOR calculate image prior
% Reg= noser_image_prior(inv_model)
% Reg        => output regularization term
% inv_model  => inverse model struct
%
% Prior is diag(diag(J'*J)^exponent)
% param is normally .5, this value can be changed by
% setting inv_model.noser_image_prior.exponent= new_value
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
    img_bkgnd= calc_jacobian_bkgnd( inv_model );
    J = calc_jacobian( inv_model.fwd_model, img_bkgnd);
    exponent= 0.5;
    if isfield(inv_model,'noser_image_prior');
       exponent= inv_model.noser_image_prior.exponent;
    end
    l_prior= size(J,2);
    % Reg is spdiags(diag(J'*J),0, l_prior, l_prior);
    diag_col= sum(J.^2,1)';
    Reg = spdiags( diag_col.^exponent, 0, l_prior, l_prior);