Description of mk_GREIT_model_mine
Home > eidors > models > a_adler > mk_GREIT_model_mine.m
mk_GREIT_model_mine
PURPOSE
MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
SYNOPSIS
function imdl= mk_GREIT_model(fmdl, radius, weight, extra_noise)
DESCRIPTION
 MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
   imdl= mk_GREIT_model( fmdl, radius, weight, extra_noise )
 Parameters
   fmdl   - fwd model on which to do simulations, or
          - string specifying prepackaged models
   radius - requested weighting matrix  (recommend 0.25 for 16 electrodes)
   weight - weighting matrix (weighting of noise vs signal)
   extra_noise - extra noise samples (such as electrode movement)
 NOTE
   currently extra_noise is not supported
   currently weighting matrix must be scalar
CROSS-REFERENCE INFORMATION
This function calls:
calc_GREIT_RM CALCULATE GREIT reconstruction matrix
fourier_fit FOURIER_FIT: use fourier series to interpolate onto a boundary
ng_mk_cyl_models NG_MAKE_CYL_MODELS: create cylindrical models using netgen
mk_image MK_IMAGE: create eidors image object
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_common_gridmdl MK_COMMON_MODEL: make EIT on reconstruction grids (GREIT)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
select_imdl SELECT_IMDL: select pre-packaged inverse model features
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
This function is called by: