Description of num_elems
num_elems
PURPOSE
NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
SYNOPSIS
function num = num_elems(mdl);
DESCRIPTION
 NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
 num_elems = num_elems( mdl );
CROSS-REFERENCE INFORMATION
This function calls:
mk_image MK_IMAGE: create eidors image object
mk_common_model MK_COMMON_MODEL: make common EIT models
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
This function is called by:
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
fix_model FIX_MODEL: Add useful fields to a model
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function num = num_elems(mdl);
% NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
% num_elems = num_elems(mdl);
% $Id$
if isstr(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
if ~isfield(mdl,'type') && isfield(mdl,'elems') % Set default for this case
   mdl.type = 'fwd_model';
end
switch mdl.type
  case 'image';      fmdl = mdl.fwd_model;
  case 'inv_model';  fmdl = mdl.fwd_model;
  case 'fwd_model';  fmdl = mdl;
  otherwise;
      error('can''t process model of type %s', mdl.type );
end
num = size(fmdl.elems,1);
function do_unit_test
   mdl = mk_common_model('a2c2',8);
   ne = num_elems( mdl );
   ok='fail'; if ne==64; ok='ok'; end; fprintf('test1: %10s\n',ok);
   ne = num_elems( mdl.fwd_model );
   ok='fail'; if ne==64; ok='ok'; end; fprintf('test2: %10s\n',ok);
   ne = num_elems( mk_image( mdl ));
   ok='fail'; if ne==64; ok='ok'; end; fprintf('test3: %10s\n',ok);
   mdl = mk_common_model('n3r2',16);
   ne = num_elems( mk_image( mdl ));
   ok='fail'; if ne==828; ok='ok'; end; fprintf('test4: %10s\n',ok);