Description of fwd_solve
fwd_solve
PURPOSE
FWD_SOLVE: calculate data from a fwd_model object and an image
SYNOPSIS
function data = fwd_solve(fwd_model, img)
DESCRIPTION
 FWD_SOLVE: calculate data from a fwd_model object and an image
 fwd_solve can be called as
    data= fwd_solve( fwd_model, img)
 or
    data= fwd_solve( img)
 in each case it will call the fwd_model.solve
                        or img.fwd_model.solve method
 For reconstructions on dual meshes, the interpolation matrix
    is defined as fwd_model.coarse2fine. If required, this takes
    coarse2fine * x_coarse = x_fine
 data      is a measurement data structure
 fwd_model is a fwd_model structure
 img       is an img structure
 Options: (not available on all solvers)
    img.fwd_solve.get_all_meas = 1 (data.volt = all FEM nodes, but not CEM)
    img.fwd_solve.get_all_nodes= 1 (data.volt = all nodes, including CEM)
CROSS-REFERENCE INFORMATION
This function calls:
eidors_model_params mdl = eidors_model_params(mdl);
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
GN_abs_solve GN_ABS_SOLVER absolute solver using Gauss Newton approximation
aa_calc_jacobian AA_CALC_JACOBIAN: J= aa_calc_jacobian(fwd_model, img)
aa_e_move_jacobian AA_E_MOVE_JACOBIAN: J= aa_e_move_jacobian(fwd_model, img)
calc_all_node_voltages CALC_ALL_NODE_VOLTAGES - calculate voltage on all nodes
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
ab_tv_diff_solve AB_TV_DIFF_SOLVE inverse solver for Andrea Borsic's
pdipm_abs PDIPM_ABS inverse solver for absolute data using Primal/Dual interior point method
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
calc_transferimpedance CALC_TRANSFERIMPEDANCE: Calculates transfer impedance matrix
bs_nonlinearGN NONLINEARGN Non-Linear EIT Inverse
calc_move_jacobian CALC_JACOBIAN Computes the Jacobian matrix for conductivity and
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
np_calc_jacobian NP_CALC_JACOBIAN: J= np_calc_jacobian(fwd_model, img)
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
cheating_2d code to simulate inverse crimes in EIT
compare_2d_algs Compare different 2D reconstructions
compare_3d_algs Compare different 3D reconstructions
demo_2d_simdata Example of using EIDORS to simulate 2D data and to
demo_3d_simdata How to make simulation data using EIDORS3D
demo_real [inhomg_img, demo_img] = demo_real;
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
manchester_tomography Example to show reconstructions from
object_in_tank_2d 2D demo example for reconstruction of object floating inside tank with
resistor_model DEMO to show really simple application of EIDORS framework
show_current SHOW_CURRENT: show current or other quantity defined
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
simulate_2d_movement SIMULATE_2D_MOVEMENT simulate rotational movement in 2D
simulate_3d_movement SIMULATE_3D_MOVEMENT simulate rotational movement in 2D
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
test_GREIT_model
calc_data_prior_test Verify dataprior:
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
perturb_jacobian_test Perturbation Jacobians
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_colour_direction Test colour mapping
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SOURCE CODE
function data = fwd_solve(fwd_model, img)
% FWD_SOLVE: calculate data from a fwd_model object and an image
%
% fwd_solve can be called as
%    data= fwd_solve(fwd_model, img)
% or
%    data= fwd_solve(img)
%
% in each case it will call the fwd_model.solve
%                        or img.fwd_model.solve method
%
% For reconstructions on dual meshes, the interpolation matrix
%    is defined as fwd_model.coarse2fine. If required, this takes
%    coarse2fine * x_coarse = x_fine
%
% data      is a measurement data structure
% fwd_model is a fwd_model structure
% img       is an img structure
%
% Options: (not available on all solvers)
%    img.fwd_solve.get_all_meas = 1 (data.volt = all FEM nodes, but not CEM)
%    img.fwd_solve.get_all_nodes= 1 (data.volt = all nodes, including CEM)
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
if nargin==1
   img= fwd_model;
   fwd_model= img.fwd_model;
end
fwd_model= eidors_model_params(fwd_model);
if isfield(fwd_model,'coarse2fine')
   c2f= fwd_model.coarse2fine;
   if size(img.elem_data,1)==size(c2f,2)
%     fwd_model data is provided on coarse mesh
      img.elem_data = c2f * img.elem_data;
   end
end
if isfield(fwd_model,'background')
    img.elem_data = img.elem_data + fwd_model.background;
end
if ~isfield(fwd_model, 'electrode')
   error('EIDORS: attempting to solve on model without electrodes');
end
if ~isfield(fwd_model, 'stimulation')
   error('EIDORS: attempting to solve on model without stimulation patterns');
end
data = feval(fwd_model.solve, fwd_model, img);
data= eidors_obj('data',data);  % create data object
eidors_obj('set-cache', img, 'fwd_solve_data', data);
eidors_msg('fwd_solve: setting cached value',3);