Description of test_compl_elec_mdl
test_compl_elec_mdl
PURPOSE
Test formation of complete electrode model
SYNOPSIS
This is a script file.
DESCRIPTION
 Test formation of complete electrode model
CROSS-REFERENCE INFORMATION
This function calls:
aa_calc_system_mat AA_CALC_SYSTEM_MAT: SS= aa_calc_system_mat(fwd_model, img)
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
mk_common_model MK_COMMON_MODEL: make common EIT models
This function is called by:
SOURCE CODE
% Test formation of complete electrode model
imdl= mk_common_model('a2c2',8);
fmdl= imdl.fwd_model;
for i=1:8;
   fmdl.electrode(i).nodes = fmdl.electrode(i).nodes + [0,1];
end
img= calc_jacobian_bkgnd(imdl);
aa_calc_system_mat(fmdl,img);
disp('success'); % if we have no errors