Description of test_3d_resistor
test_3d_resistor
PURPOSE
Create 3D model of a Rectangular resistor
SYNOPSIS
This is a script file.
DESCRIPTION
 Create 3D model of a Rectangular resistor
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
aa_calc_jacobian AA_CALC_JACOBIAN: J= aa_calc_jacobian(fwd_model, img)
aa_calc_system_mat AA_CALC_SYSTEM_MAT: SS= aa_calc_system_mat(fwd_model, img)
aa_fwd_solve AA_FWD_SOLVE: data= aa_fwd_solve(fwd_model, img)
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
find_boundary [srf, idx] = find_boundary(simp);
np_calc_jacobian NP_CALC_JACOBIAN: J= np_calc_jacobian(fwd_model, img)
np_calc_system_mat NP_CALC_SYSTEM_MAT: s_mat= np_calc_system_mat(fwd_model, img)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
show_fem SHOW_FEM: show the EIDORS3D finite element model
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
This function is called by:
SOURCE CODE
% Create 3D model of a Rectangular resistor
% $Id$
ll=5; % length
ww=1; % width
hh=1; % height
conduc= .13;  % conductivity in Ohm-meters
current= 4;  % Amps
z_contact= 1e-2;
scale = .46;
mdl= eidors_obj('fwd_model','3D rectangle');
nn=0;
for z=0:ll; for x=0:ww; for y=0:hh
   nn=nn+1;
   mdl.nodes(nn,:) = [x,y,z];
end; end; end
if 0
% Matlab's delaunayn triangularization is screwed up
   mdl.elems = delaunayn(mdl.nodes);
elseif 0
% Matlab's delaunay3 triangularization is screwed up
   mdl.elems = delaunay3(mdl.nodes(:,1), mdl.nodes(:,2), mdl.nodes(:,3));
elseif 0
   elem1= [ 1 2 3 5; 5 6 2 3; 5 6 7 3; ...
            4 2 3 8; 8 6 2 3; 8 6 7 3;];
   mdl.elems=[];
   for i=0:ll-1;
       mdl.elems= [mdl.elems; elem1+4*i];
   end
else
   mdl= mk_grid_model([],0:ww,0:hh,0:ll);
   mdl.nodes= mdl.nodes*scale;
   mdl= rmfield(mdl,'coarse2fine');
end
mdl.boundary= find_boundary(mdl.elems);
mdl.gnd_node = 1;
elec_nodes= [1:(ww+1)*(hh+1)];
elec(1).nodes= elec_nodes;      elec(1).z_contact= z_contact;
elec(2).nodes= nn-elec_nodes+1; elec(2).z_contact= z_contact;
stim.stim_pattern= [-1;1]*current;
stim.meas_pattern= [-1,1];
mdl.stimulation= stim;
mdl.electrode= elec;
show_fem(mdl);
mdl.solve = @aa_fwd_solve;
mdl.system_mat = @aa_calc_system_mat;
n_el = size(mdl.elems,1);
img= eidors_obj('image','3D rectangle', ...
      'elem_data', ones(n_el,1) * conduc, ...
      'fwd_model', mdl);
fsol= fwd_solve(img);
fprintf('Solver %s: %f\n', fsol.name, fsol.meas);
mdl.solve = @np_fwd_solve;
mdl.system_mat = @np_calc_system_mat;
mdl.misc.perm_sym= '{n}';
img= eidors_obj('image','3D rectangle', ...
      'elem_data', ones(size(mdl.elems,1),1) * conduc, ...
      'fwd_model', mdl);
fsol= fwd_solve(img);
fprintf('Solver %s: %f\n', fsol.name, fsol.meas);
% analytical solution
R = ll / ww / hh / scale/ conduc + 2*z_contact/scale^2;
V= current*R;
fprintf('Solver %s: %f\n', 'analytic', V);
% NOW CALCULATE THE ANALYTICAL JACOBIAN
mdl.solve = @np_fwd_solve;
mdl.jacobian = @np_calc_jacobian;
mg.elem_data= ones(n_el,1) * conduc ;
Jnp= calc_jacobian(mdl,img);
mdl.jacobian = @perturb_jacobian;
Jp1= calc_jacobian(mdl,img);
img.elem_data= ones(n_el,1) * conduc ;
Jp2= zeros(size(Jnp));
delta= 1e-8;
for i=1:n_el
   fsol_h= fwd_solve(img);
   img.elem_data(i) = img.elem_data(i) + delta;
   fsol_i= fwd_solve(img);
   Jp2(:,i) = (fsol_i.meas - fsol_h.meas)/delta;
end
mdl.solve = @aa_fwd_solve;
mdl.jacobian = @aa_calc_jacobian;
Jaa= calc_jacobian(mdl,img);
[Jaa;Jnp;Jp1;Jp2]