function fmdl = ng_make_cyl_models(cyl_shape, elec_pos, ...
                  elec_shape, extra_ng_code);
% NG_MAKE_CYL_MODELS: create cylindrical models using netgen
% fmdl = ng_make_cyl_models(cyl_shape, elec_pos, elec_shape, extra_ng_code);
% 
% cyl_shape = {height, [radius, [maxsz]]}
%    if height = 0 -> calculate a 2D shape
%    radius (OPT)  -> (default = 1)
%    maxsz  (OPT)  -> max size of mesh elems (default = courase mesh)
%
% ELECTRODE POSITIONS:
%  elec_pos = [n_elecs_per_plane,z_planes] 
%     OR
%  elec_pos = [x,y,z] centres of each electrode (N_elecs x 3)
%
% ELECTRODE SHAPES::
%  elec_shape = {[width,height], [maxsz] } % Rectangular elecs
%     OR
%  elec_shape = {[radius], [maxsz] }  % Circular elecs
%     OR
%  elec_shape = {[radius,0], [maxsz] }  % Circular elecs
%     maxsz  (OPT)  -> max size of mesh elems (default = courase mesh)
%
% Specify either a common electrode shape or for each electrode
%
%
% USAGE EXAMPLES:
% Simple 3D cylinder. No electrodes
%  fmdl= ng_make_cyl_models(30,{0}); 

% (C) Andy Adler, 2009. Licenced under GPL v2 or v3
% $Id$

fnstem = tempname;
geofn= [fnstem,'.geo'];
meshfn= [fnstem,'.vol'];
fid=fopen(geofn,'w');

tank_height = cyl_shape(1);
tank_radius = 1; if length(cyl_shape)>1; tank_radius=cyl_shape(2); end
tank_maxh   = 0; if length(cyl_shape)>2; tank_maxh  =cyl_shape(3); end

write_header(fid,tank_height,tank_radius,tank_maxh);
   fprintf(fid,'tlo bigcyl;\n');
fclose(fid);
   call_netgen( geofn, meshfn);

centres=[];

fmdl = ng_mk_fwd_model( meshfn, centres, 'ng', []);

function write_header(fid,tank_height,tank_radius,maxsz);
   if maxsz==0; 
      maxsz = '';
   else
      maxsz = sprintf('-maxh=%f',maxsz);
   end

   fprintf(fid,'#Automatically generated by ng_make_cyl_models\n');
   fprintf(fid,'algebraic3d\n');
   fprintf(fid,'solid cyl=cylinder (0,0,0;0,0,%6.2f;%6.2f); \n', ...
           tank_height, tank_radius);
   fprintf(fid,['solid bigcyl= plane(0,0,0;0,0,-1)\n' ...
                'and  plane(0,0,%6.2f;0,0,1)\n' ...
                'and  cyl %s;\n'],tank_height,maxsz);  
