Description of elem_dim
Home > eidors > models > a_adler > elem_dim.m
elem_dim
PURPOSE
ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
SYNOPSIS
function num = elem_dim(mdl);
DESCRIPTION
 ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
  Note, elem_dim is not the same as the model dimention (can have 2D models in 3D space)
 num_dim = elem_dim( mdl );
    = 2 if 2D, 3 if 3D
CROSS-REFERENCE INFORMATION
This function calls:
mk_image MK_IMAGE: create eidors image object
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
mk_common_model MK_COMMON_MODEL: make common EIT models
This function is called by:
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)