Description of mdl_dim
mdl_dim
PURPOSE
MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
SYNOPSIS
function num = mdl_dim(mdl);
DESCRIPTION
 MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
  Note, mdl_dims is not the same as the element dimentions
 num_dim = mdl_dim( mdl );
    = 2 if 2D, 3 if 3D
CROSS-REFERENCE INFORMATION
This function calls:
mk_image MK_IMAGE: create eidors image object
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
mk_common_model MK_COMMON_MODEL: make common EIT models
This function is called by:
eval_GREIT_fig_merit EVAL_GREIT_FIG_MERIT: calculate GREIT figures of merit for images
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
fix_model FIX_MODEL: Add useful fields to a model
calc_slices calc_slices (img, levels, clim) show slices at levels of an
show_fem SHOW_FEM: show the EIDORS3D finite element model
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function num = mdl_dim(mdl);
% MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
%  Note, mdl_dims is not the same as the element dimentions
% num_dim = mdl_dim(mdl);
%    = 2 if 2D, 3 if 3D
% $Id$
if isstr(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
if ~isfield(mdl,'type') && isfield(mdl,'nodes') % Set default for this case
   mdl.type = 'fwd_model';
end
switch mdl.type
  case 'image';      fmdl = mdl.fwd_model;
  case 'inv_model';  fmdl = mdl.fwd_model;
  case 'fwd_model';  fmdl = mdl;
  otherwise;
      error('can''t process model of type %s', mdl.type );
end
num = size(fmdl.nodes,2);
function do_unit_test
   mdl = mk_common_model('a2c2',8);
   ne = mdl_dim( mdl );
   ok='fail'; if ne==2; ok='ok'; end; fprintf('test1: %10s\n',ok);
   mdl = mk_common_model('n3r2',16);
   ne = mdl_dim( mk_image( mdl ));
   ok='fail'; if ne==3; ok='ok'; end; fprintf('test2: %10s\n',ok);