Description of fem_master_full
fem_master_full
PURPOSE
function [E,D,Ela,pp] = fem_master_full(vtx,simp,mat,gnd_ind,elec,zc,perm_sym);
SYNOPSIS
function [E,D,Ela,pp] = fem_master_full(vtx,simp,mat,gnd_ind,elec,zc,perm_sym);
DESCRIPTION
function [E,D,Ela,pp] = fem_master_full(vtx,simp,mat,gnd_ind,elec,zc,perm_sym);
Builds up the system matrix based on the complete electrode model. E is not
yet permuted. To permute E -> E(pp,pp) as in forward_solver.
E       = The full rank system matrix based on the 3D complete electrode model
D       = The sgradients of the shape functions over each element.
Ela     = Normalised volums of the elements
pp      = Column permutation vector, for more help type help symmmd
vtx     = The vertices matrix
simp    = The simplices matrix
mat     = The conductivity vector
gnd_ind = The index of the ground node
elec    = The bounary electrodes matrix
zc      = The contact impedance vector, satisfying size(elec,1) = length(zc)
perm_sym= Column permutation of E, either '{y}' to opt or '{n}' to avoid.
CROSS-REFERENCE INFORMATION
This function calls:
bld_master_full function [Ef,D,Ela] = bld_master_full(vtx,simp,mat,elec,zc);
ref_master function [Er] = ref_master(E,vtx,gnd_ind,sch);
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
inv_solve_dual_mesh INV_SOLVE_DUAL_MESH using a coarse and fine mesh
adjoint_spin function [JTb] = adjoint_spin(vtx,simp,elec,x,gnd_ind,zc,I,no_pl,Vmes);
inverse_solver function [solf,solp] = inverse_solver(I,voltage,tol,mat_ref,vtx,simp,elec,no_pl,zc,perm_sym,gnd_ind,tfac,Reg,it);
jacobian_3d function [J] = jacobian_3d(I,elec,vtx,simp,gnd_ind,mat_ref,zc,v_f,df,tol,perm_sym);
np_calc_system_mat NP_CALC_SYSTEM_MAT: s_mat= np_calc_system_mat(fwd_model, img)
demo_complex This demo function shows how the EIT problem can be formulated in a complex
demo_real_test Perform tests based on the demo_real function
SOURCE CODE
function [E,D,Ela,pp] = fem_master_full(vtx,simp,mat,gnd_ind,elec,zc,perm_sym);
%function [E,D,Ela,pp] = fem_master_full(vtx,simp,mat,gnd_ind,elec,zc,perm_sym);
%
%Builds up the system matrix based on the complete electrode model. E is not
%yet permuted. To permute E -> E(pp,pp) as in forward_solver.
%
%
%
%E       = The full rank system matrix based on the 3D complete electrode model
%D       = The sgradients of the shape functions over each element.
%Ela     = Normalised volums of the elements
%pp      = Column permutation vector, for more help type help symmmd
%vtx     = The vertices matrix
%simp    = The simplices matrix
%mat     = The conductivity vector
%gnd_ind = The index of the ground node
%elec    = The bounary electrodes matrix
%zc      = The contact impedance vector, satisfying size(elec,1) = length(zc)
%perm_sym= Column permutation of E, either '{y}' to opt or '{n}' to avoid.
   [Ef,D,Ela] = bld_master_full(vtx,simp,mat,elec,zc);
   [E] = ref_master(Ef,vtx,gnd_ind);
% use symmmd in old matlab (pre v7)
ver= eidors_obj('interpreter_version');
if ~ver.isoctave && ver.ver<7.0
    pp = symmmd(E);
else
    pp = symamd(E);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This is part of the EIDORS suite.
% Copyright (c) N. Polydorides 2003
% Copying permitted under terms of GNU GPL
% See enclosed file gpl.html for details.
% EIDORS 3D version 2.0
% MATLAB version 5.3 R11
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%