Description of find_boundary
find_boundary
PURPOSE
[srf, idx] = find_boundary(simp);
SYNOPSIS
function [srf, idx] = find_boundary(simp);
DESCRIPTION
 [srf, idx] = find_boundary(simp);
Caclulates the boundary faces of a given 3D volume.
Usefull in electrode assignment.
srf  =  array of elements on each boundary simplex
        boundary simplices are of 1 lower dimention than simp
idx  =  index of simplex to which each boundary belongs
simp = The simplices matrix
CROSS-REFERENCE INFORMATION
This function calls:
find_boundary [srf, idx] = find_boundary(simp);
eidors_msg EIDORS_MSG: eidors progress and status messages
mk_common_model MK_COMMON_MODEL: make common EIT models
This function is called by:
aa_fwd_parameters AA_FWD_PARAMETERS: data= aa_fwd_solve(fwd_model, image)
fix_model FIX_MODEL: Add useful fields to a model
eidors_model_params mdl = eidors_model_params(mdl);
find_boundary [srf, idx] = find_boundary(simp);
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
demo_real [inhomg_img, demo_img] = demo_real;
show_fem SHOW_FEM: show the EIDORS3D finite element model
dm_2d_pt_elecs DM_2D_PT_ELECS: Create circle mesh (or radius 1) refined
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
ng_mk_cyl_models NG_MAKE_CYL_MODELS: create cylindrical models using netgen
ng_mk_ellip_models NG_MAKE_ELLIP_MODELS: create elliptical models using netgen
ng_mk_extruded_model NG_MAKE_EXTRUDED_MODEL: create extruded models using netgen
ng_mk_gen_models NG_MAKE_ELLIP_MODELS: create elliptical models using netgen
fwd_model_from_v2 CREATE EIDORS v3 fwd_model from the v2 variables
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_fmdl_from_nodes MK_FMDL_FROM_NODES: create fmdl from nodes
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
set_fwd_model SET_FWD_MODEL: create EIDORS v3 fwd_model from v2 parameters
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
test_3d_resistor Create 3D model of a Rectangular resistor
SUBFUNCTIONS
function [srf,idx]= find_2or3d_boundary(simp,dim);
function do_unit_test
function bdy= sort_boundary(bdy)
function ok= match(pat1, pat2, ok, descr)
SOURCE CODE
function [srf, idx] = find_boundary(simp);
% [srf, idx] = find_boundary(simp);
%
%Caclulates the boundary faces of a given 3D volume.
%Usefull in electrode assignment.
%
%srf  =  array of elements on each boundary simplex
%        boundary simplices are of 1 lower dimention than simp
%idx  =  index of simplex to which each boundary belongs
%simp = The simplices matrix
% $Id$
if isstr(simp) && strcmp(simp,'UNIT_TEST'); do_unit_test; return; end
if isstruct(simp) && strcmp(simp.type,'fwd_model'); simp= simp.elems; end
wew = size(simp,2) - 1;
if wew==3 || wew==2
   [srf,idx]= find_2or3d_boundary(simp,wew);
else
   eidors_msg('find_boundary: WARNING: not 2D or 3D simplices',1);
   srf=[]; return;
end
% sort surfaces. If there is more than one, its not on the boundary
function [srf,idx]= find_2or3d_boundary(simp,dim);
   if size(simp,1) < 4e9 % max of uint32
      % convert to integer to make sort faster
      simp = uint32( simp );
   end
   localface = nchoosek(1:dim+1,dim);
   srf_local= simp(:,localface');
   srf_local= reshape( srf_local', dim, []); % D x 3E
   srf_local= sort(srf_local)'; % Sort each row
   [sort_srl,sort_idx] = sortrows( srf_local );
   % Fine the ones that are the same
   first_ones =  sort_srl(1:end-1,:);
   next_ones  =  sort_srl(2:end,:);
   same_srl = find( all( first_ones == next_ones, 2) );
   % Assume they're all different. then find the same ones
   diff_srl = logical(ones(size(srf_local,1),1));
   diff_srl(same_srl) = 0;
   diff_srl(same_srl+1) = 0;
   srf= sort_srl( diff_srl,: );
   idx= sort_idx( diff_srl);
   idx= ceil(idx/(dim+1));
function do_unit_test
ok=1;
%2D Test:
mdl = mk_common_model('c2c',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
ok= match(bdy,bdyc,ok,'2D test');
%3D Test:
mdl = mk_common_model('n3r2',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
ok= match(bdy,bdyc,ok,'3D test n3r2');
%3D Test:
mdl = mk_common_model('a3cr',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
ok= match(bdy,bdyc,ok,'3D test a3c2');
%3D Test:
mdl = mk_common_model('b3cr',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
ok= match(bdy,bdyc,ok,'3D test b3c2');
function bdy= sort_boundary(bdy)
   bdy = sort(bdy,2);
   bdy = sortrows(bdy);
function ok= match(pat1, pat2, ok, descr)
    ok =  all(pat1(:) == pat2(:));
    fprintf('find_bounday_test: ok=%d\n',ok);
% function ok= match(pat1, pat2, ok, descr)
%    if ~all(pat1(:) == pat2(:))
%       ok=0;
%       eidors_msg('find_bounday_test: fail %s',descr,1);
%    end