Description of np_fwd_solve
np_fwd_solve
PURPOSE
NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
SYNOPSIS
function data= np_fwd_solve(fwd_model, img)
DESCRIPTION
 NP_FWD_SOLVE: data= np_fwd_solve( fwd_model, img)
 Fwd solver for Nick Polydorides EIDORS3D code
 Input:
    fwd_model = forward model
    img       = image struct
 Output:
    data = measurements struct
 Options: (to return internal FEM information)
    img.fwd_solve.get_all_meas = 1 (data.volt = all FEM nodes, but not CEM)
    img.fwd_solve.get_all_nodes= 1 (data.volt = all nodes, including CEM)
CROSS-REFERENCE INFORMATION
This function calls:
calc_system_mat CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
forward_solver [V] = forward_solver(E,I,tol,pp,V);
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
This function is called by:
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
perturb_jacobian_test Perturbation Jacobians
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
SOURCE CODE
function data= np_fwd_solve(fwd_model, img)
% NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
% Fwd solver for Nick Polydorides EIDORS3D code
% Input:
%    fwd_model = forward model
%    img       = image struct
% Output:
%    data = measurements struct
% Options: (to return internal FEM information)
%    img.fwd_solve.get_all_meas = 1 (data.volt = all FEM nodes, but not CEM)
%    img.fwd_solve.get_all_nodes= 1 (data.volt = all nodes, including CEM)
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
p= np_fwd_parameters(fwd_model);
%Set the tolerance for the forward solver
tol = 1e-5;
s_mat= calc_system_mat(fwd_model, img);
Vfwd = forward_solver(s_mat.E, p.I, tol, s_mat.perm);
Velec=Vfwd(p.n_node+(1:p.n_elec),:);
voltH = zeros(p.n_meas, 1);
idx=0;
for i=1:p.n_stim
   meas_pat= fwd_model.stimulation(i).meas_pattern;
   n_meas  = size(meas_pat,1);
   voltH( idx+(1:n_meas) ) = meas_pat*Velec(:,i);
   idx= idx+ n_meas;
end
% create a data structure to return
data.meas= voltH;
data.time= -1; % unknown
data.name= 'solved by np_fwd_solve';
try; if img.fwd_solve.get_all_meas == 1
   data.volt = Vfwd(1:p.n_node,:); % but not on CEM nodes
end; end
try; if img.fwd_solve.get_all_nodes== 1
   data.volt = Vfwd;               % all, including CEM nodes
end; end