all: eidors-eit2015-oneslide.pdf eidors-eit2015-poster.pdf
eidors-eit2015-oneslide.pdf: eidors-eit2015-oneslide.tex
	pdflatex -halt-on-error $<
	pdflatex -halt-on-error $<
	pdflatex -halt-on-error $<
eidors-eit2015-poster.pdf: eidors-eit2015-poster.tex
	pdflatex -halt-on-error $<
	pdflatex -halt-on-error $<
	pdflatex -halt-on-error $<

