Description of create_tank_mesh_ng
Home > eidors > meshing > netgen > create_tank_mesh_ng.m
create_tank_mesh_ng
PURPOSE
USAGE: [tank_mdl,centres] = create_tank_mesh_ng(...
SYNOPSIS
function [tank_mdl,centres] = create_tank_mesh_ng(tank_radius, tank_height,CorR, log2_electrodes_per_plane,no_of_planes,first_plane_starts, height_between_centres,electrode_width, electrode_height,fnstem, elec_mesh_density)
DESCRIPTION
USAGE: [tank_mdl,centres] = create_tank_mesh_ng(...
           tank_radius, tank_height,CorR, log2_electrodes_per_plane, ...
           no_of_planes,first_plane_starts, height_between_centres,  ...
           electrode_width, electrode_height,fnstem, elec_mesh_density )
 Parameters  tank_radius, tank_height,
   CorR= 'C' for circular 'R' for rectangular
  log2_electrodes_per_plane  that is 2^this electrodes per plane
, no_of_planes,..
  number_of_planes,
  first_plane_starts  z coordinate were centre of first plane starts
, height_between_centres   of electrode planes ,
 electrode_width, electrode_height , the width is just radius if 'R'
  fnstem the file name used for saving netgen files
 elec_mesh_density  - minimum size of element on electrodes.
              Default is no enhanced electrodes
 Function to generate tank model
 Bill Lionheart 23/01/2005 (somewhere over Siberia)
 Part of EIDORS 3D
 Revised for new version 3.0 structure WRBL 05/12/2005
Made in to function WRBL 6/5/2005
 $Id: create_tank_mesh_ng.m 1950 2009-11-21 16:14:37Z aadler $
CROSS-REFERENCE INFORMATION
This function calls:
writengcuboid writes the specification for a netgen cuboid on fid, named name, centerd on c,
call_netgen CALL_NETGEN: call netgen to create a vol_file from a geo_file
ng_mk_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
This function is called by:
create_tank_mesh_ng_interactive Script to generate tank model interactively
move_the_ball Takes a netgen geo file with a ball in and moves it around