Description of move_the_ball
Home > eidors > meshing > netgen > move_the_ball.m
move_the_ball
PURPOSE
Takes a netgen geo file with a ball in and moves it around
SYNOPSIS
This is a script file.
DESCRIPTION
 Takes a netgen geo file with a ball in and moves it around
 First make the mesh
Inputs are: (and defaults)
    electrodes_per_plane = 16;
    number_of_planes     = 2;
    movement_pattern     = 'spiral',
                           'spirograph'
                           'radial_move'
                           'vertical_move'
  Example
    electrodes_per_plane = 16;  number_of_planes = 2; move_the_ball
  Output:
    output is saved to netgen_moving_ball.mat
 (C) 2005 Bill Lionheart. Licensed under GPL v2
 - mods by Andy Adler to allow higher density electrode models
 $Id: move_the_ball.m 1593 2008-07-29 15:06:21Z aadler $
CROSS-REFERENCE INFORMATION
This function calls:
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
triarea3d [ta] = triarea3d(V);
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
crop_model CROP_MODEL: Crop away parts of a fem model
show_fem SHOW_FEM: show the EIDORS3D finite element model
call_netgen CALL_NETGEN: call netgen to create a vol_file from a geo_file
create_tank_mesh_ng USAGE: [tank_mdl,centres] = create_tank_mesh_ng(...
ng_mk_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
This function is called by: