Description of shape_scrapbook
Home > eidors > meshing > netgen > shape_scrapbook.m
shape_scrapbook
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
fourier_fit FOURIER_FIT: use fourier series to interpolate onto a boundary
ng_mk_extruded_model NG_MAKE_EXTRUDED_MODEL: create extruded models using netgen
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
This function is called by: