Description of unit_test_cmp
unit_test_cmp
PURPOSE
UNIT_TEST_CMP: compare matrices in eidors output
SYNOPSIS
function unit_test_cmp(txt,a,b,tol)
DESCRIPTION
 UNIT_TEST_CMP: compare matrices in eidors output
 unit_test_cmp(txt,a,b,tol)
 if a==b print ok, otherwise print fail
CROSS-REFERENCE INFORMATION
This function calls:
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
get_img_data GET_IMG_DATA: get parameter data from eidors image object
calc_colours [colours,scl_data]= calc_colours(img, set_value, do_colourbar)
calc_slices calc_slices (img, levels, clim) show slices at levels of an
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
inv_solve INV_SOLVE: calculate imag from an inv_model and data
mk_image MK_IMAGE: create eidors image object
elem_select ELEM_SELECT: select element fractions inside a function
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
reciprocity_idx RECIPROCITY_IDX: find indices of stim, meas pairs that are recirocal
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
SOURCE CODE
function unit_test_cmp(txt,a,b,tol)
% UNIT_TEST_CMP: compare matrices in eidors output
% unit_test_cmp(txt,a,b,tol)
% if a==b print ok, otherwise print fail
% License GPL v2 or v3: $Id$
   if nargin==1 && strcmp(txt,'UNIT_TEST');
         unit_test_cmp('UNIT_TEST_CMP: OK',1,.99,.02); return;
   end
   if nargin < 4; tol = 0; end
   fprintf('TEST: %20s = ',txt);
   ok='fail';
   try; if isnan(a) == isnan(b); a(isnan(a))=0; b(isnan(b))=0; end; end
   try; if all(abs(a - b) <= tol);  ok='ok'; end; catch; end
   disp(ok)
%  if ~strcmp(ok,'ok'); keyboard; end