Description of UpdateFemMatrix
Home > eidors > models > m_vauhkonen > UpdateFemMatrix.m
UpdateFemMatrix
PURPOSE
UpdateFemMatrix Assembles the system matrix for EIT
SYNOPSIS
function [A]=UpdateFemMatrix(Agrad,Kb,M,S,sigma);
DESCRIPTION
UpdateFemMatrix Assembles the system matrix for EIT
 Function [A]=UpdateFemMatrix(Agrad,Kb,M,S,sigma);
 updates the system matrix A given a new conductivity
 vector sigma.
 INPUT
 Agrad = the gradient part of the system matrix (see FemMatrix.m)
 Kb,M and S = other blocks of the system matrix (see FemMatrix.m)
 sigma = conductivity (or admittivity) vector
 OUTPUT
 A = the updated system matrix
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ErrorFunc
mv_calc_system_mat MV_CALC_SYSTEM_MAT: s_mat= mv_calc_system_mat(fwd_model, img)
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis