Description of calc_model_prior_test
calc_model_prior_test
PURPOSE
Verify model prior calcs
SYNOPSIS
function ok= calc_model_prior_test;
DESCRIPTION
 Verify model prior calcs
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
gaussian_HPF_prior GAUSSIAN_HPF_PRIOR calculate image prior
laplace_image_prior LAPLACE_IMAGE_PRIOR calculate image prior
noser_image_prior NOSER_IMAGE_PRIOR calculate image prior
tikhonov_image_prior TIKHONOV_IMAGE_PRIOR calculate image prior
ab_calc_tv_prior AB_CALC_TV_PRIOR calculate Total Variation image prior
calc_R_prior R = calc_R_prior(inv_model, varargin)
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
eidors_cache Control eidors_caching
mk_common_model MK_COMMON_MODEL: make common EIT models
This function is called by:
SOURCE CODE
function ok= calc_model_prior_test;
% Verify model prior calcs
% $Id$
% TODO: also test the various inverse prior calls
imdl= mk_common_model('c2c2',16);
try; imdl= rmfield(imdl,'RtR_prior'); end
try; imdl= rmfield(imdl,'R_prior');   end
any_priors= {@tikhonov_image_prior, ...
             @noser_image_prior, ...
             @gaussian_HPF_prior, ...
             @laplace_image_prior};
R_priors=   {any_priors{:}, ...
             @ab_calc_tv_prior};
% Call R_priors as R_priors
eidors_cache clear
for i = 1:length(R_priors); p = R_priors{i};
   inv_mdl= imdl;
   inv_mdl.R_prior= p;
   R= calc_R_prior(inv_mdl);
   fprintf('R_prior: %20s  R_condest= %5.4g\n', func2str(p), condest(R'*R));
end
% Call R_priors as RtR_priors
eidors_cache clear
for i = 1:length(R_priors); p = R_priors{i};
   inv_mdl= imdl;
   inv_mdl.R_prior= p;
   RtR= calc_RtR_prior(inv_mdl);
   fprintf('R_prior: %20s  RtR_condest= %5.4g\n', func2str(p), condest(RtR));
end
% Call RtR_priors as RtR_priors
eidors_cache clear
for i = 1:length(R_priors); p = R_priors{i};
   inv_mdl= imdl;
   inv_mdl.RtR_prior= p;
   RtR= calc_RtR_prior(inv_mdl);
   if diff(size(RtR))~=0  % non-square
      fprintf('RtR_prior: %20s  RtR_condest= NON-SQUARE\n', func2str(p) );
   else
      fprintf('RtR_prior: %20s  RtR_condest= %5.4g\n', func2str(p), condest(RtR));
   end
end
% Call RtR_priors as R_priors
eidors_cache clear
for i = 1:length(R_priors); p = R_priors{i};
   inv_mdl= imdl;
   inv_mdl.RtR_prior= p;
   if strcmp(func2str(p), 'ab_calc_tv_prior')
      continue; % not fair to ask it to ichol a non-square matrix
   end
   R= calc_R_prior(inv_mdl);
   fprintf('RtR_prior: %20s  R_condest= %5.4g\n', func2str(p), condest(R'*R));
end