%urlwrite( ...
%'http://eidors3d.sourceforge.net/data_contrib/dg_geophysical_EIT/Mine_20FEV2004.zip', 'Mine_20FEV2004.zip');
zipfilecontents = unzip('../../data_contrib/dg_geophysical_EIT/Mine_20FEV2004.zip');
