Description of ng_mk_ext_fwd_model
Home > eidors > meshing > netgen > ng_mk_ext_fwd_model.m
ng_mk_ext_fwd_model
PURPOSE
NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
SYNOPSIS
function [fwd_mdl, mat_indices]=ng_mk_fwd_model(ng_vol_filename, centres,name, stim_pattern, z_contact)
DESCRIPTION
 NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
 [fwd_mdl, mat_indices]= ...
      ng_mk_fwd_model( ng_vol_filename, centres, ...
                       name, stim_pattern, z_contact)
  ng_vol_filename:   filename output from netgen
  name:              name for object (if [] use ng_vol_filename)
  centres:           matrix of N x [x,y,z] electrode centres
                     centres can also be a Nx1 cell matrix of
                     functions which are 1 inside the electrode and 0 outside
  stim_pattern:      a stimulation pattern structure
                     empty ([]) if stim_pattern is not available
  z_contact:         vector or scalar electrode contact impedance
  fwd_mdl:           eidors format fwd_model
  mat_indices:       cell array of material indices from eidors
CROSS-REFERENCE INFORMATION
This function calls:
aa_calc_jacobian AA_CALC_JACOBIAN: J= aa_calc_jacobian(fwd_model, img)
aa_calc_system_mat AA_CALC_SYSTEM_MAT: SS= aa_calc_system_mat(fwd_model, img)
aa_fwd_solve AA_FWD_SOLVE: data= aa_fwd_solve(fwd_model, img)
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
ng_read_mesh [srf,vtx,fc,bc,simp,edg,mat_ind] = ng_read_mesh(filename)
ng_tank_find_elec [elec,sels, electrodes] = ng_tank_find_elec(srf,vtx,fc,centres);
This function is called by: