Description of ng_read_mesh
Home > eidors > meshing > netgen > ng_read_mesh.m
ng_read_mesh
PURPOSE
[srf,vtx,fc,bc,simp,edg,mat_ind] = ng_read_mesh(filename)
SYNOPSIS
function[srf,vtx,fc,bc,simp,edg,mat_ind] = ng_read_mesh(filename)
DESCRIPTION
[srf,vtx,fc,bc,simp,edg,mat_ind] = ng_read_mesh(filename)
 Function to read in a mesh model from NetGen and saves it in
 five arrays; surface (srf), veritices (vtx), face no. (fc)
 volume (simp) and edges (edg)
 Version 4.0
 B.D.Grieve - 27/01/2002 + modifications by lmazurk
 A.Adler - 2006 mods to run quicker
 EIDORS's srf array is a subset of NetGen's surface element data
 (columns 6:8). The first column of the surface element data also
 ascribes a face number to each surface which is saved as the fc
 array. Each line of the srf array contains 3 indices to define
 a triangle mapped on to the three dimensional vtx array.
 EIDORS's vtx array is a direct equivalent to NetGen's pointer data.
 srf      = The surfaces indices into vtx
 simp     = The volume indices into vtx
 vtx      = The vertices matrix
 fc       = A one column matrix containing the face numbers
 edg      = Edge segment information
 filename = Name of file containing NetGen .vol information
 mat_ind  = Material index
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
This function is called by:
create_cylinder_mesh_ng USAGE: cylinder_mdl = create_cylinder_mesh_ng(basename ...
ng_mk_ext_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
ng_mk_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file