Description of calc_jacobian_bkgnd
calc_jacobian_bkgnd
PURPOSE
CALC_JACOBIAN_BKGND: calculate background image around
SYNOPSIS
function img_bkgnd = calc_jacobian_bkgnd(inv_model)
DESCRIPTION
 CALC_JACOBIAN_BKGND: calculate background image around
    which initial estimate of jacobian is calculated
 img_bkgnd = calc_jacobian_bkgnd( inv_model )
 inv_model   is an EIDORS fwd_model
 img_bkgnd   is an EIDORS struct
 Usage:
      The background for calc_jacobian may be specified
      as an estimated value
  inv_model.jacobian_bkgnd.value;  % scalar OR
                                   % vector of Nx1
 Usage:
      The background may be calculated by a function
  inv_model.jacobian_bkgnd.func;
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
GN_abs_solve GN_ABS_SOLVER absolute solver using Gauss Newton approximation
aa_inv_conj_grad AA_INV_CONJ_GRAD inverse solver based on the CG
aa_inv_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
aa_inv_total_var AA_INV_TOTAL_VARIANCE inverse solver for difference EIT
inv_kalman_diff INV_KALMAN_DIFF inverse solver for difference EIT
nodal_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
noser_image_prior NOSER_IMAGE_PRIOR calculate image prior
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
time_prior_solve TIME_PRIOR_SOLVE inverse solver to account for time differences
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
pdipm_abs PDIPM_ABS inverse solver for absolute data using Primal/Dual interior point method
pdipm_diff PDIPM_DIFF inverse solver for difference data using Primal/Dual interior point method
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
get_img_data GET_IMG_DATA: get parameter data from eidors image object
mcmc_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
fourD_prior_solve fourD_prior_solve-- inverse solver to account for temporal
calc_slices calc_slices (img, levels, clim) show slices at levels of an
show_current SHOW_CURRENT: show current or other quantity defined
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_slices out_img = show_slices (img, levels) show slices at levels of an
perturb_jacobian_test Perturbation Jacobians
test_c2f_jacobian Test calc of jacobian given coarse to fine mapping
test_compl_elec_mdl Test formation of complete electrode model
SOURCE CODE
function img_bkgnd = calc_jacobian_bkgnd(inv_model)
% CALC_JACOBIAN_BKGND: calculate background image around
%    which initial estimate of jacobian is calculated
%
% img_bkgnd = calc_jacobian_bkgnd(inv_model)
% inv_model   is an EIDORS fwd_model
% img_bkgnd   is an EIDORS struct
%
% Usage:
%      The background for calc_jacobian may be specified
%      as an estimated value
%  inv_model.jacobian_bkgnd.value;  % scalar OR
%                                   % vector of Nx1
%
% Usage:
%      The background may be calculated by a function
%  inv_model.jacobian_bkgnd.func;
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
img_bkgnd= eidors_obj('get-cache', inv_model, 'jacobian_bkgnd');
if ~isempty(img_bkgnd)
   eidors_msg('calc_jacobian_bkgnd: using cached value', 3);
   return
end
if isfield(inv_model.jacobian_bkgnd,'func')
   img_bkgnd= feval( inv_model.jacobian_bkgnd.func, inv_model );
else
   % allow bkgnd to be scalar or vector
   fwd_model= inv_model.fwd_model;
   bkgnd = ones(size(fwd_model.elems,1),1);
   bkgnd(:)= inv_model.jacobian_bkgnd.value;
   img_bkgnd= eidors_obj('image', 'homog image', ...
                         'elem_data', bkgnd, ...
                         'fwd_model', fwd_model );
end
eidors_obj('set-cache', inv_model, 'jacobian_bkgnd', img_bkgnd);
eidors_msg('jacobian_bkgnd: setting cached value', 3);