Description of calc_jacobian
calc_jacobian
PURPOSE
CALC_JACOBIAN: calculate jacobian from an inv_model
SYNOPSIS
function J = calc_jacobian(fwd_model, img)
DESCRIPTION
 CALC_JACOBIAN: calculate jacobian from an inv_model
  J = calc_jacobian( fwd_model, img )
  J = calc_jacobian( img )
      calc Jacobian on fwd_model at conductivity given
      in image (fwd_model is for forward and reconstruction)
 For reconstructions on dual meshes, the interpolation matrix
    is defined as fwd_model.coarse2fine. This takes
    coarse2fine * x_coarse = x_fine
 If the underlying jacobian calculator doesn't understand dual
    meshes, then calc_jacobian will automatically postmultiply
    by fwd_model.coarse2fine.
 img       is an image structure, with 'elem_data' or
           'node_data' parameters
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
GN_abs_solve GN_ABS_SOLVER absolute solver using Gauss Newton approximation
aa_inv_conj_grad AA_INV_CONJ_GRAD inverse solver based on the CG
aa_inv_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
aa_inv_total_var AA_INV_TOTAL_VARIANCE inverse solver for difference EIT
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
inv_kalman_diff INV_KALMAN_DIFF inverse solver for difference EIT
jacobian_elem2nodes JACOBIAN_ELEM2NODES: calculate Jacobian on Nodes from Elem solver
nodal_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
noser_image_prior NOSER_IMAGE_PRIOR calculate image prior
perturb_jacobian PERTURB_JACOBIAN: J= perturb_jacobian(fwd_model, img)
time_prior_solve TIME_PRIOR_SOLVE inverse solver to account for time differences
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
pdipm_abs PDIPM_ABS inverse solver for absolute data using Primal/Dual interior point method
pdipm_diff PDIPM_DIFF inverse solver for difference data using Primal/Dual interior point method
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
bs_nonlinearGN NONLINEARGN Non-Linear EIT Inverse
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
mcmc_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
fourD_prior_solve fourD_prior_solve-- inverse solver to account for temporal
resistor_model DEMO to show really simple application of EIDORS framework
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
calc_data_prior_test Verify dataprior:
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
perturb_jacobian_test Perturbation Jacobians
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function cache_obj= jacobian_cache_params(fwd_model, img);
SOURCE CODE
function J = calc_jacobian(fwd_model, img)
% CALC_JACOBIAN: calculate jacobian from an inv_model
%
%  J = calc_jacobian(fwd_model, img)
%  J = calc_jacobian(img)
%      calc Jacobian on fwd_model at conductivity given
%      in image (fwd_model is for forward and reconstruction)
%
% For reconstructions on dual meshes, the interpolation matrix
%    is defined as fwd_model.coarse2fine. This takes
%    coarse2fine * x_coarse = x_fine
%
% If the underlying jacobian calculator doesn't understand dual
%    meshes, then calc_jacobian will automatically postmultiply
%    by fwd_model.coarse2fine.
%
% img       is an image structure, with 'elem_data' or
%           'node_data' parameters
% (C) 2005-08 Andy Adler. License: GPL version 2 or version 3
% $Id$
if nargin==1
   img       = fwd_model;
   fwd_model = img.fwd_model;
end
cache_obj= jacobian_cache_params(fwd_model, img);
J= eidors_obj('get-cache', cache_obj, 'jacobian');
if ~isempty(J)
   eidors_msg('calc_jacobian: using cached value', 3);
   return
end
J= feval(fwd_model.jacobian, fwd_model, img);
if isfield(fwd_model,'coarse2fine')
   c2f= fwd_model.coarse2fine;
   if size(J,2)==size(c2f,1)
%     calc_jacobian did not take into account the coarse2fine
      J=J*c2f;
   end
end
eidors_obj('set-cache', cache_obj, 'jacobian', J);
eidors_msg('calc_jacobian: setting cached value', 3);
% Make the Jacobian only depend on
function cache_obj= jacobian_cache_params(fwd_model, img);
   if isfield(img, 'elem_data')
      cache_obj = {fwd_model, img.elem_data};
   elseif isfield(img, 'node_data')
      cache_obj = {fwd_model, img.node_data};
   else
      error('calc_jacobian: execting elem_data or node_data in image');
   end