Description of triarea3d
Home > eidors > algorithms > n_polydorides > triarea3d.m
triarea3d
PURPOSE
[ta] = triarea3d(V);
SYNOPSIS
function [ta] = triarea3d(V);
DESCRIPTION
[ta] = triarea3d(V);
Function that calculates the area of a triangle
in the 3D Cartesian space.
V = the 3 x 3 coordinates matrix of the points, first
column for the xs and last for the zs.
ta = the area of the triangle
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bld_master_full function [Ef,D,Ela] = bld_master_full(vtx,simp,mat,elec,zc);
iso_f_smooth function [Reg] = iso_f_smooth(simp,vtx,deg,w);
move_the_ball Takes a netgen geo file with a ball in and moves it around