Description of calc_TSVD_RM
calc_TSVD_RM
PURPOSE
CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
SYNOPSIS
function RM= calc_TSVD_RM(mdl,hp)
DESCRIPTION
 CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
   RM= calc_TSVD_RM(mdl, hp)
   RM    => reconstruction matrix
   mdl   => an inverse or forward model structure
   hp    => hyperparameter. Ratio between the last kept and the first SV
            in percent (default: 1)
 SEE ALSO: inv_solve_TSVD, solve_use_matrix
CROSS-REFERENCE INFORMATION
This function calls:
solve_use_matrix SOLVE_USE_MATRIX solve using reconstruction matrix
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
mk_image MK_IMAGE: create eidors image object
mk_common_model MK_COMMON_MODEL: make common EIT models
This function is called by:
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function RM= calc_TSVD_RM(mdl,hp)
% CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
%   RM= calc_TSVD_RM(mdl, hp)
%
%   RM    => reconstruction matrix
%   mdl   => an inverse or forward model structure
%   hp    => hyperparameter. Ratio between the last kept and the first SV
%            in percent (default: 1)
%
% SEE ALSO: inv_solve_TSVD, solve_use_matrix
% (C) 2011 Bartlomiej Grychtol. Licenced under GPL v2 or v3
% $Id$
if isstr(mdl) && strcmp(mdl, 'UNIT_TEST'), do_unit_test, return,end
switch (mdl.type)
    case 'inv_model'
        fmdl = mdl.fwd_model;
        bkgnd_img = calc_jacobian_bkgnd(mdl);
    case 'fwd_model'
        fmdl = mdl;
        bkgnd_img = mk_image( fmdl,1) ;
    otherwise
        eidors_msg('calc_TSVD_RM: Object type not supported');
end
if nargin < 2
    hp = 1;
end
J= calc_jacobian(fmdl,bkgnd_img);
imdl.solve = @solve_use_matrix;
S = eidors_obj('get-cache',mdl,'TSVD_S');
if isempty(S)
    [U,S,V] = svd(J,'econ');
    eidors_obj('set-cache',mdl,'TSVD_S',S);
    eidors_obj('set-cache',mdl,'TSVD_V',V);
    eidors_obj('set-cache',mdl,'TSVD_U',U);
else
    U = eidors_obj('get-cache',mdl,'TSVD_U');
    V = eidors_obj('get-cache',mdl,'TSVD_V');
end
s = diag(S);
s = s./s(1);
N = find(s >= hp/100,1,'last'); %disp(N);
t= 1:N; % tsvd
RM = eidors_obj('get-cache',mdl,'TSVD_RM',N);
if isempty(RM)
    RM  = (V(:,t)/S(t,t))*U(:,t)';
    eidors_obj('set-cache',mdl,'TSVD_RM',RM,N);
end
function do_unit_test
mdl = mk_common_model('b3t2r',[16,1]);
RM = calc_TSVD_RM(mdl);