Description of calc_system_mat
calc_system_mat
PURPOSE
CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
SYNOPSIS
function system_mat = calc_system_mat(fwd_model, img)
DESCRIPTION
 CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
    system_mat= calc_system_mat( fwd_model, image)
 OR
    system_mat= calc_system_mat( image)
 it will call the fwd_model.solve
 system_mat
   system_mat.E    is FEM system_matrix
   system_mat.perm is permutation of E  i.e. E(perm,perm)
 fwd_model is a fwd_model structure
 image     is an image structure
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
aa_calc_jacobian AA_CALC_JACOBIAN: J= aa_calc_jacobian(fwd_model, img)
aa_fwd_solve AA_FWD_SOLVE: data= aa_fwd_solve(fwd_model, img)
calc_move_jacobian CALC_JACOBIAN Computes the Jacobian matrix for conductivity and
mv_fwd_solve MV_FWD_SOLVE: data= mv_fwd_solve(fwd_model, img)
np_calc_3d_fields NP_CALC_3D_FIELDS: J= np_calc_3d_fields(fwd_model, img)
np_calc_jacobian NP_CALC_JACOBIAN: J= np_calc_jacobian(fwd_model, img)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
SOURCE CODE
function system_mat = calc_system_mat(fwd_model, img)
% CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
%
%    system_mat= calc_system_mat(fwd_model, image)
% OR
%    system_mat= calc_system_mat(image)
%
% it will call the fwd_model.solve
%
% system_mat
%   system_mat.E    is FEM system_matrix
%   system_mat.perm is permutation of E  i.e. E(perm,perm)
% fwd_model is a fwd_model structure
% image     is an image structure
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
if nargin==1
   img = fwd_model;
   fwd_model = img.fwd_model;
end
cache_obj= {fwd_model, img.elem_data};
system_mat= eidors_obj('get-cache', cache_obj, 'system_mat');
if ~isempty(system_mat)
   eidors_msg('system_mat: using cached value', 3);
   return
end
system_mat= feval(fwd_model.system_mat, fwd_model, img);
eidors_obj('set-cache', cache_obj, 'system_mat', system_mat);
eidors_msg('calc_system_mat: setting cached value', 3);