Description of calc_RtR_prior
calc_RtR_prior
PURPOSE
RtR = calc_RtR_prior(inv_model)
SYNOPSIS
function RtR_prior = calc_RtR_prior(inv_model)
DESCRIPTION
 RtR = calc_RtR_prior( inv_model )
 CALC_RtR_PRIOR: calculate image regularization prior
   R'*R (which is an estimate of the inverse of the covariance)
   Typically, the image prior is matrix n_elem x n_elem of the
   normalized a priori crosscorrelation FEM element values
 calc_RtR_prior can be called as
    RtR_prior= calc_RtR_prior( inv_model, ... )
 and will call the function inv_model.RtR_prior
 parameters to RtR_prior should be passed in the field
 inv_model.RtR_prior_function_name.parameters
 if there exists a field inv_model.rec_model, then
   the prior is calculated on the rec_model rather than
   the fwd_model. This will not be done if
 inv_model.prior_use_fwd_not_rec= 1;
 RtR_prior    the calculated RtR regularization prior
 inv_model    is an inv_model structure
 If a function to calculate RtR_prior is not provided,
 RtR = R_prior' * R_prior;
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
GN_abs_solve GN_ABS_SOLVER absolute solver using Gauss Newton approximation
aa_e_move_image_prior AA_E_MOVE_IMAGE_PRIOR calculate image prior
aa_inv_conj_grad AA_INV_CONJ_GRAD inverse solver based on the CG
aa_inv_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
inv_kalman_diff INV_KALMAN_DIFF inverse solver for difference EIT
nodal_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
time_prior_solve TIME_PRIOR_SOLVE inverse solver to account for time differences
bs_nonlinearGN NONLINEARGN Non-Linear EIT Inverse
inv_solve_dual_mesh INV_SOLVE_DUAL_MESH using a coarse and fine mesh
mcmc_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
calc_model_prior_test Verify model prior calcs
SUBFUNCTIONS
function inv_model = rec_or_fwd_model(inv_model);
SOURCE CODE
function RtR_prior = calc_RtR_prior(inv_model)
% RtR = calc_RtR_prior(inv_model)
% CALC_RtR_PRIOR: calculate image regularization prior
%   R'*R (which is an estimate of the inverse of the covariance)
%
%   Typically, the image prior is matrix n_elem x n_elem of the
%   normalized a priori crosscorrelation FEM element values
%
% calc_RtR_prior can be called as
%    RtR_prior= calc_RtR_prior(inv_model, ...)
%
% and will call the function inv_model.RtR_prior
% parameters to RtR_prior should be passed in the field
% inv_model.RtR_prior_function_name.parameters
%
% if there exists a field inv_model.rec_model, then
%   the prior is calculated on the rec_model rather than
%   the fwd_model. This will not be done if
% inv_model.prior_use_fwd_not_rec= 1;
%
% RtR_prior    the calculated RtR regularization prior
% inv_model    is an inv_model structure
%
% If a function to calculate RtR_prior is not provided,
% RtR = R_prior' * R_prior;
% (C) 2005-2008 Andy Adler. License: GPL version 2 or version 3
% $Id$
inv_model = rec_or_fwd_model(inv_model);
RtR_prior = eidors_obj('get-cache', inv_model, 'RtR_prior');
if ~isempty(RtR_prior)
   eidors_msg('calc_RtR_prior: using cached value', 3);
   return
end
if isfield(inv_model,'RtR_prior')
   RtR_prior= feval( inv_model.RtR_prior, inv_model );
elseif isfield(inv_model,'R_prior')
   % The user has provided an R prior. We can use this to
   % calculate RtR= R'*R;
   R= feval( inv_model.R_prior, inv_model );
   RtR_prior = R'*R;
else
   error('calc_RtR_prior: neither R_prior or RtR_prior func provided');
end
if isfield(inv_model.fwd_model,'coarse2fine')
   c2f= inv_model.fwd_model.coarse2fine;
   if size(RtR_prior,1)==size(c2f,1)
%     we need to take into account coarse2fine - using a reasonable tol
      eidors_msg('calc_RtR_prior: using coarse2fine to model RtR');
      f2c= c2f'; %pinv(c2f,1e-6);
      RtR_prior=c2f'*RtR_prior*c2f;
   end
end
eidors_obj('set-cache', inv_model, 'RtR_prior', RtR_prior);
eidors_msg('calc_RtR_prior: setting cached value', 3);
function inv_model = rec_or_fwd_model(inv_model);
   if isfield(inv_model,'rec_model');
      use_rec_model = 1;
      try if inv_model.prior_use_fwd_not_rec== 1;
         use_rec_model = 0;
      end; end
      if use_rec_model
         inv_model.fwd_model= inv_model.rec_model;
         inv_model= rmfield(inv_model,'rec_model');
      end
   end