Description of calc_hyperparameter
calc_hyperparameter
PURPOSE
CALC_HYPERPARAMETER: calculate hyperparameter value
SYNOPSIS
function hyperparameter = calc_hyperparameter(inv_model)
DESCRIPTION
 CALC_HYPERPARAMETER: calculate hyperparameter value
   The hyperparameter is can be either provided directly,
     or can be based an automatic selection approach
 calc_hyperparameter can be called as
    hyperparameter= calc_hyperparameter( inv_model )
 where inv_model    is an inv_model structure
 if inv_model.hyperparameter.func exists, it will be
   called, otherwise inv_model.hyperparameter.value will
   be returned
 TODO: does hyperparameter depend on inv_model, or does
       it also depend on the data?
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
GN_abs_solve GN_ABS_SOLVER absolute solver using Gauss Newton approximation
aa_inv_conj_grad AA_INV_CONJ_GRAD inverse solver based on the CG
aa_inv_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
aa_inv_total_var AA_INV_TOTAL_VARIANCE inverse solver for difference EIT
inv_kalman_diff INV_KALMAN_DIFF inverse solver for difference EIT
nodal_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
time_prior_solve TIME_PRIOR_SOLVE inverse solver to account for time differences
ab_tv_diff_solve AB_TV_DIFF_SOLVE inverse solver for Andrea Borsic's
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
pdipm_abs PDIPM_ABS inverse solver for absolute data using Primal/Dual interior point method
pdipm_diff PDIPM_DIFF inverse solver for difference data using Primal/Dual interior point method
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
bs_nonlinearGN NONLINEARGN Non-Linear EIT Inverse
inv_solve_dual_mesh INV_SOLVE_DUAL_MESH using a coarse and fine mesh
mcmc_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
fourD_prior_solve fourD_prior_solve-- inverse solver to account for temporal
SOURCE CODE
function hyperparameter = calc_hyperparameter(inv_model)
% CALC_HYPERPARAMETER: calculate hyperparameter value
%   The hyperparameter is can be either provided directly,
%     or can be based an automatic selection approach
%
% calc_hyperparameter can be called as
%    hyperparameter= calc_hyperparameter(inv_model)
% where inv_model    is an inv_model structure
%
% if inv_model.hyperparameter.func exists, it will be
%   called, otherwise inv_model.hyperparameter.value will
%   be returned
%
% TODO: does hyperparameter depend on inv_model, or does
%       it also depend on the data?
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
if isfield(inv_model.hyperparameter, 'func')
   hyperparameter = eidors_obj('get-cache', inv_model, 'hyperparameter');
   if ~isempty(hyperparameter)
      eidors_msg('calc_hyperparameter: using cached value', 2);
      return
   end
   hyperparameter= feval( inv_model.hyperparameter.func, inv_model);
   eidors_obj('set-cache', inv_model, 'hyperparameter', hyperparameter);
   eidors_msg('calc_hyperparameter: setting cached value', 2);
else
    hyperparameter= inv_model.hyperparameter.value;
end