Description of calc_meas_icov
calc_meas_icov
PURPOSE
meas_icov = calc_meas_icov(inv_model)
SYNOPSIS
function meas_icov = calc_meas_icov(inv_model)
DESCRIPTION
 meas_icov = calc_meas_icov( inv_model )
 CALC_MEAS_ICOV: calculate inverse covariance of measurements
   The meas_icov is a matrix n_meas x n_meas of the
     inverse of measurement covariances. Normally measurements
     are assumed to be independant, so the meas_icov is
     a diagonal matrix of 1/var(meas)
 calc_meas_icov can be called as
    meas_icov= calc_meas_icov( inv_model )
 meas_icov   is the calculated data prior
 inv_model    is an inv_model structure
 if:
    inv_model.meas_icov    is a function
          -> call it to calculate meas_icov
    inv_model.meas_icov    is a matrix
          -> return it as meas_icov
    inv_model.meas_icov    does not exist
          -> use I, or 1./homg (for normalized difference)
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG: eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
This function is called by:
GN_abs_solve GN_ABS_SOLVER absolute solver using Gauss Newton approximation
aa_inv_conj_grad AA_INV_CONJ_GRAD inverse solver based on the CG
aa_inv_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
aa_inv_total_var AA_INV_TOTAL_VARIANCE inverse solver for difference EIT
inv_kalman_diff INV_KALMAN_DIFF inverse solver for difference EIT
nodal_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
time_prior_solve TIME_PRIOR_SOLVE inverse solver to account for time differences
pdipm_abs PDIPM_ABS inverse solver for absolute data using Primal/Dual interior point method
pdipm_diff PDIPM_DIFF inverse solver for difference data using Primal/Dual interior point method
fourD_prior_solve fourD_prior_solve-- inverse solver to account for temporal
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
SUBFUNCTIONS
function meas_icov = default_meas_icov(inv_model)
function n_meas = calc_n_meas(fwd_model)
function homg_data = solve_homg_image(fwd_mdl)
SOURCE CODE
function meas_icov = calc_meas_icov(inv_model)
% meas_icov = calc_meas_icov(inv_model)
% CALC_MEAS_ICOV: calculate inverse covariance of measurements
%   The meas_icov is a matrix n_meas x n_meas of the
%     inverse of measurement covariances. Normally measurements
%     are assumed to be independant, so the meas_icov is
%     a diagonal matrix of 1/var(meas)
%
% calc_meas_icov can be called as
%    meas_icov= calc_meas_icov(inv_model)
%
% meas_icov   is the calculated data prior
% inv_model    is an inv_model structure
%
% if:
%    inv_model.meas_icov    is a function
%          -> call it to calculate meas_icov
%    inv_model.meas_icov    is a matrix
%          -> return it as meas_icov
%    inv_model.meas_icov    does not exist
%          -> use I, or 1./homg (for normalized difference)
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
meas_icov = eidors_obj('get-cache', inv_model, 'meas_icov');
if ~isempty(meas_icov)
   eidors_msg('calc_meas_icov: using cached value', 3);
   return
end
if isfield(inv_model,'meas_icov')
   if isnumeric(inv_model.meas_icov);
      meas_icov = inv_model.meas_icov;
   else
      meas_icov= feval( inv_model.meas_icov, inv_model);
   end
else
   meas_icov= default_meas_icov( inv_model );
end
eidors_obj('set-cache', inv_model, 'meas_icov', meas_icov);
eidors_msg('calc_meas_icov: setting cached value', 3);
% Calculate a data prior for an assumption of uniform noise
% on each channel
%
function meas_icov = default_meas_icov(inv_model)
   fwd_model= inv_model.fwd_model;
   if isfield(fwd_model,'normalize_measurements')
      normalize = fwd_model.normalize_measurements;
   else
      normalize = 0;
   end
   n =  calc_n_meas( fwd_model );
   if ~normalize
      meas_icov= speye( n );
   else
      homg_data=  solve_homg_image( fwd_model );
% sig = k/h -> std = k/h -> 1/std = kh
      meas_icov = sparse(1:n, 1:n, ( homg_data.meas ).^2 );
   end
function n_meas = calc_n_meas(fwd_model)
   n_meas = 0;
   for i= 1:length(fwd_model.stimulation );
       n_meas = n_meas + size(fwd_model.stimulation(i).meas_pattern,1);
   end
% create homogeneous image + simulate data
function homg_data = solve_homg_image(fwd_mdl)
    n_elems= size( fwd_mdl.elems , 1);
    mat= ones( n_elems, 1);
    homg_img= eidors_obj('image', 'homogeneous image', ...
                         'elem_data', mat, 'fwd_model', fwd_mdl );
    homg_data=fwd_solve( homg_img);