Description of eidors_model_params
eidors_model_params
PURPOSE
mdl = eidors_model_params(mdl);
SYNOPSIS
function mdl = eidors_model_params(mdl);
DESCRIPTION
 mdl = eidors_model_params( mdl );
 Fill in default parameter values in EIDORS types
 (C) 2006 Andy Adler. Licensed under the GPL v2
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
eidors_model_params mdl = eidors_model_params(mdl);
find_boundary [srf, idx] = find_boundary(simp);
This function is called by:
eidors_model_params mdl = eidors_model_params(mdl);
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
inv_solve INV_SOLVE: calculate imag from an inv_model and data
SOURCE CODE
function mdl = eidors_model_params(mdl);
% mdl = eidors_model_params(mdl);
% Fill in default parameter values in EIDORS types
%
% (C) 2006 Andy Adler. Licensed under the GPL v2
% $Id$
% TODO - to caching
try
   type=mdl.type;
catch
   error('eidors_model_params: object is not eidors object (no type)');
end
switch type;
   case 'inv_model';
      mdl.fwd_model= eidors_model_params( mdl.fwd_model );
      if ~isfield(mdl,'reconst_type');
         mdl.reconst_type= 'difference';
      end
   case 'fwd_model';
      if ~isfield(mdl,'normalize_measurements');
         mdl.normalize_measurements= 0;
      end
      if ~isfield(mdl,'elems');
         return;
      end
      mdl.elems=    double(mdl.elems);
      if isfield(mdl,'boundary')
         mdl.boundary= double(mdl.boundary);
      else
         mdl.boundary= find_boundary(mdl.elems);
      end
      % fill in boundary if it doesn't exist
      mdl.n_elem = size(mdl.elems,1);
      mdl.n_node = size(mdl.nodes,1);
      if isfield(mdl,'electrode');
         mdl.n_elec = length(mdl.electrode);
      else
         mdl.n_elec = 0;
      end
end