Description of eidors_msg
eidors_msg
PURPOSE
EIDORS_MSG: eidors progress and status messages
SYNOPSIS
function log_level= eidors_msg(message, varargin)
DESCRIPTION
EIDORS_MSG: eidors progress and status messages
 USAGE: eidors_msg('mission accomplished; time to relax', 1)
   prints 'EIDORS:[ mission accomplished; time to relax ]'
       if log_level <=1
   less important messages have higher levels
 other parameters will be sent to print; example
 eidors_msg('did %d of %s at %f', 2, 'stuff', sqrt(2), 1)
   prints 'EIDORS:[ did 2 of stuff at 1.414214 ]'
 USAGE: eidors_msg( 'log_level', 1)
   sets the loglevel to 1
 USAGE: eidors_msg( 'log_level2', 3)
   sets the loglevel2 to 3
 meanings of levels
   0 => keep quiet (no messages should be level=0)
   1 => important messages
   2 => most messages
   3 => detailed information
 Messages at log_level are displayed
 Messages at log_level2 are displayed temprorarily
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
aa_fwd_parameters AA_FWD_PARAMETERS: data= aa_fwd_solve(fwd_model, image)
aa_inv_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
aa_inv_total_var AA_INV_TOTAL_VARIANCE inverse solver for difference EIT
aa_system_mat_fields AA_SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
backproj_solve BACKPROJ_SOLVE inverse solver using backprojection
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
choose_noise_figure CHOOSE_NOISE_FIGURE: choose hyperparameter based on NF calculation
eval_GREIT_fig_merit EVAL_GREIT_FIG_MERIT: calculate GREIT figures of merit for images
gaussian_HPF_prior GAUSSIAN_HPF_PRIOR calculate image prior
inv_kalman_diff INV_KALMAN_DIFF inverse solver for difference EIT
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_coarse_fine_mapping MK_COARSE_FINE_MAPPING: create a mapping matrix from coarse to fine FEM
nodal_solve AA_INV_SOLVE inverse solver using approach of Adler&Guardo 1996
time_prior_solve TIME_PRIOR_SOLVE inverse solver to account for time differences
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_transferimpedance CALC_TRANSFERIMPEDANCE: Calculates transfer impedance matrix
bs_nonlinearGN NONLINEARGN Non-Linear EIT Inverse
calc_move_jacobian CALC_JACOBIAN Computes the Jacobian matrix for conductivity and
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
calc_R_prior R = calc_R_prior(inv_model, varargin)
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
calc_hyperparameter CALC_HYPERPARAMETER: calculate hyperparameter value
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
calc_system_mat CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
edge_refined_elem_mapper EDGE_REFINED_ELEM_MAPPER: map elements from coarse to dense model
edge_refined_node_mapper EDGE_REFINED_NODE_MAPPER:
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
mv_calc_system_mat MV_CALC_SYSTEM_MAT: s_mat= mv_calc_system_mat(fwd_model, img)
mv_fwd_parameters MV_FWD_PARAMETERS: data= mv_fwd_solve(fwd_model)
find_boundary [srf, idx] = find_boundary(simp);
forward_solver [V] = forward_solver(E,I,tol,pp,V);
np_calc_image_prior NP_CALC_IMAGE_PRIOR calculate image prior
np_calc_system_mat NP_CALC_SYSTEM_MAT: s_mat= np_calc_system_mat(fwd_model, img)
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
fourD_prior_solve fourD_prior_solve-- inverse solver to account for temporal
eidors_cache Control eidors_caching
demo_real [inhomg_img, demo_img] = demo_real;
moving_tank_objs MOVING_TANK_OBJS: create movies of objects moving in tanks
resistor_model DEMO to show really simple application of EIDORS framework
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
calc_slices calc_slices (img, levels, clim) show slices at levels of an
image_levels IMAGE_LEVELS(img, levels, clim) show slices at levels of an image
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
print_convert PRINT_CONVERT: print figures and call imagemagick to trim them
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts)
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_slices out_img = show_slices (img, levels) show slices at levels of an
eidors_readdata EIDORS readdata - read data files from various EIT equipment
inv_solve INV_SOLVE: calculate imag from an inv_model and data
distmeshnd DISTMESHND N-D Mesh Generator using Distance Functions.
dm_2d_circ_pt_elecs DM_2D_CIRC_PT_ELECS: Create circle mesh (or radius 1) refined with electrodes
call_netgen CALL_NETGEN: call netgen to create a vol_file from a geo_file
ng_read_mesh [srf,vtx,fc,bc,simp,edg,mat_ind] = ng_read_mesh(filename)
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
select_imdl SELECT_IMDL: select pre-packaged inverse model features
simulate_3d_movement SIMULATE_3D_MOVEMENT simulate rotational movement in 2D
mk_library_model MK_LIBRARY_MODEL - FEM models based on library shapes
shape_library SHAPE_LIBRARY Common shapes for models
startup Script to start EIDORS
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
demo_real_test Perform tests based on the demo_real function
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
mk_stim_patterns_test Verify mk_stim_patterns function
tutorials_test TUTORIAL_TEST: Run all tutorials
SUBFUNCTIONS
function [log_level, log_level2] = get_levels;
SOURCE CODE
function log_level= eidors_msg(message, varargin)
%EIDORS_MSG: eidors progress and status messages
%
% USAGE: eidors_msg('mission accomplished; time to relax', 1)
%   prints 'EIDORS:[ mission accomplished; time to relax ]'
%       if log_level <=1
%   less important messages have higher levels
%
% other parameters will be sent to print; example
% eidors_msg('did %d of %s at %f', 2, 'stuff', sqrt(2), 1)
%   prints 'EIDORS:[ did 2 of stuff at 1.414214 ]'
%
% USAGE: eidors_msg('log_level', 1)
%   sets the loglevel to 1
% USAGE: eidors_msg('log_level2', 3)
%   sets the loglevel2 to 3
%
% meanings of levels
%   0 => keep quiet (no messages should be level=0)
%   1 => important messages
%   2 => most messages
%   3 => detailed information
%
% Messages at log_level are displayed
% Messages at log_level2 are displayed temprorarily
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id$
global eidors_objects
if nargin==1
   args= {};
   level= 2;
else
   level= varargin{ nargin-1 };
   args= varargin( 1:nargin-2 );
end
[log_level, log_level2] = get_levels;
for i= 1:length(args)
   if isa( args{i}, 'function_handle')
      args{i} = func2str(args{i});
   end
end
% It makes sense to print to stderr (fid=2), but matlab>7 prints this in red
ver= eidors_obj('interpreter_version');
if ver.ver>=7; fid= 1;
else ;         fid= 2; end
%try, lms= eidors_objects.last_message_size;
%  if lms>0; fprintf(fid,'%c', 8*ones(lms,1)); end
%end
% Need to do twice to interpret text in message
% message= sprintf(message, args{:});
if length(message)>1 % single characters are just for progress
   string= ['EIDORS:[',message,']\n'];
elseif strcmp(message, 'log_level');
   log_level= eidors_objects.log_level;
else
   string= message;
end
if strcmp(message,'log_level')
   eidors_objects.log_level= level;
elseif level <= log_level
   fprintf(fid, string, args{:});
   if exist('OCTAVE_VERSION'); fflush(fid); end
   eidors_objects.last_message_size= 0;
elseif 0 %level <= log_level2
% TODO, save messages, and write them out via (printing-hyperlinks)
%   so that users can see them.
   fprintf(fid, string);
   eidors_objects.last_message_size= length(string);
end
function [log_level, log_level2] = get_levels;
   global eidors_objects
   try
      log_level= eidors_objects.log_level;
   catch
      log_level= 2; % default;
      eidors_objects.log_level= log_level;
   end
   try
      log_level2= eidors_objects.log_level2;
   catch
      log_level2= 4; % default;
      eidors_objects.log_level2= log_level2;
   end