Description of mk_image
mk_image
PURPOSE
MK_IMAGE: create eidors image object
SYNOPSIS
function img= mk_image(mdl, elem_data, name)
DESCRIPTION
 MK_IMAGE: create eidors image object
   img= mk_image(mdl, elem_data, name)
 Utility function to create an eidors_image object:
 Usage 1:
   img = mk_image( inv_model )  -> uses jacobian backgnd for conductivity
 Usage 2: mdl can be a fwd_model or inv_model
   img = mk_image( mdl, 1 ) -> uniform image with conductivity 1
   img = mk_image( mdl, 2*ones(n_elems,1) ) -> uniform with c=2
   img = mk_image( mdl, 1, 'This name') -> Specify a 'name' attribute
 Usage 3: create image from previous image, override conductity
  img = mk_image( other_image, 2 ) -> image with c=2
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
mk_image MK_IMAGE: create eidors image object
mk_common_model MK_COMMON_MODEL: make common EIT models
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
calc_slices calc_slices (img, levels, clim) show slices at levels of an
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts)
show_current SHOW_CURRENT: show current or other quantity defined
inv_solve INV_SOLVE: calculate imag from an inv_model and data
mk_image MK_IMAGE: create eidors image object
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
select_imdl SELECT_IMDL: select pre-packaged inverse model features
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
test_GREIT_model
mk_library_model MK_LIBRARY_MODEL - FEM models based on library shapes
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function img= mk_image(mdl, elem_data, name)
% MK_IMAGE: create eidors image object
%   img= mk_image(mdl, elem_data, name)
%
% Utility function to create an eidors_image object:
% Usage 1:
%   img = mk_image(inv_model)  -> uses jacobian backgnd for conductivity
%
% Usage 2: mdl can be a fwd_model or inv_model
%   img = mk_image(mdl, 1) -> uniform image with conductivity 1
%   img = mk_image(mdl, 2*ones(n_elems,1)) -> uniform with c=2
%   img = mk_image(mdl, 1, 'This name') -> Specify a 'name' attribute
%
% Usage 3: create image from previous image, override conductity
%  img = mk_image(other_image, 2) -> image with c=2
% (C) 2008-10 Andy Adler. Licenced under GPL version 2 or 3
% $Id$
if isstr(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
if nargin<3; name = 'Created by mk_image'; end
if nargin<2;
   try
     elem_data = mdl.jacobian_bkgnd.value;
   catch
     error('mk_image: for one parameter, needs a mdl.jacobian_bkgnd field');
   end
end
switch mdl.type
   case 'inv_model'; mdl = mdl.fwd_model;
   case 'fwd_model'; mdl = mdl; % keep model
   case 'image';     mdl = mdl.fwd_model;
   otherwise; error('mk_image: no inv_model, fwd_model or image object');
end
img = eidors_obj('image',name);
img.fwd_model = mdl;
img.elem_data = NaN*ones(size(mdl.elems,1),1);
img.elem_data(:) = elem_data;
% TESTS:
function do_unit_test
   imdl = mk_common_model('a2c2',8);
   im0 = mk_image( imdl );
   unit_test_cmp('im1',im0.elem_data, ones(64,1) );
   im0 = mk_image( imdl, 2 );
   unit_test_cmp('im2',im0.elem_data, 2*ones(64,1) );
   im0 = mk_image( imdl.fwd_model, 3*ones(64,1) );
   unit_test_cmp('im3',im0.elem_data, 3*ones(64,1) );