function PSF= GREIT_desired_img_original(xyc, radius, opt)
%GREIT_DESIRED_IMG_ORIGINAL The original desired solution for GREIT
% PSF= GREIT_desired_img_original(xyc, radius, opt)
%   xyc     - array of point centers [2xNpoints]
%   radius  - the radius of the target on the desired image as a fraction
%             of the model radius (half the larger dimension in xy)
%   opt     - a struct with these mandatory fields:
%      .imgsz   size of the image in pixels [1x2]
%      .meshsz  coordinates of the image in space [xmin xmax ymin ymax]
%
% The images generated by this function are compatible with models created 
% by MK_GRID_MODEL. It only supports rectangular models and equal-size
% pixels.
%
% NOTE that the amount of blur provided by this function decreases as the
% resolution of the image increases. 
%
% As of 2015-03-29, the default desired image function used by
% MK_GRID_MODEL is MK_DESIRED_IMAGE_SIGMOID.
%
% See also: CALC_GREIT_RM, MK_GREIT_MODEL, MK_DESIRED_IMG_SIGMOID

% (C) 2009 Andy Adler. Licenced under GPL v2 or v3
% $Id$

   c_obj = {xyc, radius, opt};
   PSF = eidors_obj('get-cache', c_obj, 'desired_solution');
   if ~isempty(PSF)
       return
   end
        
   xsz = opt.imgsz(1); ysz = opt.imgsz(2);
   sz= xsz * ysz;
   xmin = opt.meshsz(1); xmax = opt.meshsz(2);
   ymin = opt.meshsz(3); ymax = opt.meshsz(4);
   % scale radius to half the greater dimension
   radius = radius * 0.5 * max(xmax-xmin, ymax-ymin);
   [x,y]= ndgrid(linspace(xmin,xmax,xsz), linspace(ymin,ymax,ysz));
   x_spc = (xmax-xmin)/(xsz-1) * 0.5;
   y_spc = (ymax-ymin)/(ysz-1) * 0.5;
   PSF = zeros(sz,size(xyc,2));
   for i=1:size(xyc,2);
      for dx = linspace(-x_spc, x_spc, 5)
         for dy = linspace(-y_spc, y_spc, 5)
            PSF(:,i) = PSF(:,i) +  1/25*( ...
               (dx+x(:)-xyc(1,i)).^2 + (dy+y(:)-xyc(2,i)).^2 ...
                        < radius^2 );
         end
      end
%     PSF(:,i) = PSF(:,i)/sum(PSF(:,i));
   end
   eidors_obj('set-cache', c_obj, 'desired_solution', PSF);
   
end

