function elec=extractElectrodesIndices(number_of_electrodes,surf)
% elec = extractElectrodesIndices(number_of_electrodes,surf)
% 
% Used with readngneutral.m file and extracts the electrodes 
% elements from the surf matrix
% number_of_electrodes: Number of electrodes
% surf: Matrix generated by readngneutral.m containing surface elements
% elec: returns a [number_of_electrodes X 6] matrix that contains the electrode elements  
%
% Umer Zeeshan Ijaz 01/11/2004
% Cheju National University, South Korea

for i=1:number_of_electrodes
    X=find(surf(:,1)==i);
    elec(i,1:3)=surf(X(1),2:4);
    elec(i,4:6)=surf(X(2),2:4);
end
